/// The 19-service Service Bank — static, canonical content.
///
/// ---------------------------------------------------------------------------
/// Part 2 item 1 — hardcoded constant, not seeded into Firestore (justified)
/// ---------------------------------------------------------------------------
/// This content is identical for every user, never changes at runtime, and
/// is needed by both apps on every open of the Services tab. Seeding it into
/// Firestore would mean a real network read (and a real cost) every single
/// time either app shows this screen, for data that is exactly as static as
/// the source code itself. A Dart constant costs nothing to read, ships with
/// the app, and cannot be edited into an inconsistent state at runtime the
/// way a guide accidentally editing a Firestore doc could.
///
/// ---------------------------------------------------------------------------
/// Part 2 item 4 — one source, not two diverging copies
/// ---------------------------------------------------------------------------
/// This file was transcribed ONCE, directly from `D:\folk-updates\SERVICE_BANK_CONTENT.txt`
/// (read in full first — confirmed 19 complete services, none truncated,
/// every one ending in a real "Assessment question:" line), then COPIED
/// VERBATIM, byte-for-byte, into the Student app at the identical relative
/// path `lib/utils/ServiceBankContent.dart`. This is the same "temporary
/// duplicate, single source of truth" treatment already used in this
/// project for `DashboardTile`/`DottedBorderBox` (Phase 5) — except here
/// there is no "old file" being phased out on one side; both copies are
/// meant to persist, so if this content is ever revised, BOTH files must be
/// updated together. If it needs to change, edit `SERVICE_BANK_CONTENT.txt`
/// first, then update both `ServiceBankContent.dart` files identically —
/// there is no shared Dart package between these two independent apps to
/// pull from a single import instead.
///
/// ---------------------------------------------------------------------------
/// Part 2 item 3 — diacritics preserved faithfully
/// ---------------------------------------------------------------------------
/// The source file is confirmed UTF-8. Every diacritic (kīrtana, prasādam,
/// mṛdaṅga, sādhana, ārati, arcana, Vaiṣṇava, Kṛṣṇa, Prabhupāda, mahā-mantra,
/// kartāla, āśrama, yātrā, Kṛṣṇa-kathā, ācāryas, sevak, Dāl, Sabjī, Chapāti)
/// is transcribed exactly as it appears in the source — none simplified to
/// plain ASCII, none silently transliterated.
library;

/// One of the 19 services. `nuance` and `context` are both genuinely
/// optional — 6 of the 19 services in the source file have no nuance line,
/// and only 7 have the extra historical/contextual paragraph that follows
/// some (not all) assessment questions. Neither is invented where the
/// source has none.
class ServiceBankEntry {
  /// 1-19, matches `serviceAssignments.serviceNumber` (Part 3).
  final int number;
  final String title;
  final List<String> subPoints;

  /// The "Nuance:" / "Crucial nuance:" / "Critical culture:" line, verbatim
  /// including whichever of those three labels the source uses — absent
  /// (null) for the 6 services that have none.
  final String? nuance;

  /// The unlabeled historical/contextual paragraph that follows some
  /// services' assessment question in the source (e.g. book distribution's
  /// note on Prabhupāda's own emphasis) — not a nuance, not a sub-point.
  /// Absent for the 12 services that have none.
  final String? context;

  final String assessmentQuestion;

  const ServiceBankEntry({
    required this.number,
    required this.title,
    required this.subPoints,
    this.nuance,
    this.context,
    required this.assessmentQuestion,
  });
}

const List<ServiceBankEntry> kServiceBank = [
  ServiceBankEntry(
    number: 1,
    title: "Kīrtana Seva — not musical performance, but congregational devotion",
    subPoints: [
      "Becoming a good responder before becoming a leader.",
      "Correct pronunciation of the mahā-mantra.",
      "Learning standard prayers and bhajans.",
      "Understanding the meaning of prayers.",
      "Basic kartāla.",
      "Basic mṛdaṅga.",
      "Rhythm and tempo.",
      "Voice discipline.",
      "Call-and-response sensitivity.",
      "Knowing how long to lead.",
      "Reading the congregation.",
      "Kīrtana appropriate to morning program, ārati, harināma, youth program and festival.",
      "Creating participation rather than displaying one's musical talent.",
      "Supporting another leader without competing.",
      "Humility when not selected to lead.",
      "Instrument maintenance.",
      "Training juniors.",
    ],
    nuance: "Crucial nuance: watch carefully for performance ego, celebrity mentality and musical domination.",
    assessmentQuestion: "Does his kīrtana make other people want to chant?",
  ),
  ServiceBankEntry(
    number: 2,
    title: "Book Distribution and Literature Seva",
    subPoints: [
      "Understanding why Prabhupāda emphasized books.",
      "Personally reading the books being distributed.",
      "Learning how to approach strangers respectfully.",
      "Opening conversations.",
      "Discovering another person's interests.",
      "Presenting the book relevantly.",
      "Explaining what the book contains.",
      "Handling common objections.",
      "Asking confidently without becoming aggressive.",
      "Maintaining honesty about donations.",
      "Respecting rejection.",
      "Learning street distribution.",
      "Campus distribution.",
      "Festival distribution.",
      "Congregational book distribution.",
      "Book-table management.",
      "Follow-up after distribution.",
      "Keeping distribution records.",
      "Setting personal/team goals.",
      "Teaching others book distribution.",
    ],
    nuance: "Nuance: numbers are important, but never cultivate manipulation, guilt or dishonesty merely to increase numbers.",
    assessmentQuestion: "Can he independently go out, engage people and place Prabhupāda's books with dignity?",
    context: "Book distribution remains an explicitly identified ISKCON ministry, and historical accounts repeatedly show Prabhupāda integrating morning spiritual practice, preaching and book distribution rather than treating book distribution as peripheral.",
  ),
  ServiceBankEntry(
    number: 3,
    title: "Preaching and Communication Seva",
    subPoints: [
      "One-to-one conversation.",
      "Two-minute explanation of Kṛṣṇa consciousness.",
      "Five-minute presentation.",
      "Fifteen-minute class.",
      "Thirty-to-forty-five-minute structured talk.",
      "Storytelling.",
      "Using analogies.",
      "Asking good questions.",
      "Listening before speaking.",
      "Explaining philosophy without jargon.",
      "Speaking to atheists.",
      "Speaking to culturally Hindu audiences.",
      "Speaking to completely new students.",
      "Speaking to parents.",
      "Speaking to professors/professionals.",
      "Handling difficult questions.",
      "Saying \u201cI don't know\u201d when appropriate.",
      "Preparing a class from Prabhupāda's books.",
      "Giving references.",
      "Voice and presentation skills.",
      "Stage confidence.",
      "Moderating discussions.",
      "Facilitating small groups.",
    ],
    assessmentQuestion: "Can he make Kṛṣṇa consciousness understandable and attractive without diluting it?",
  ),
  ServiceBankEntry(
    number: 4,
    title: "Campus Outreach Seva",
    subPoints: [
      "Identifying appropriate colleges and student communities.",
      "Campus mapping.",
      "Making first contact.",
      "Friendship-building.",
      "Inviting students.",
      "Classroom/hostel invitations where appropriate.",
      "Setting up stalls.",
      "Small introductory programs.",
      "Clubs and student groups.",
      "Permission and institutional dealings.",
      "Event promotion.",
      "Contact collection with appropriate consent.",
      "Follow-up systems.",
      "Converting an event attendee into a regular participant.",
      "Converting regular participants into serious students.",
      "Building a campus team.",
      "Training a student to become the local campus leader.",
      "Succession before seniors graduate.",
    ],
    assessmentQuestion: "Can this student eventually establish and sustain a preaching group in his own college?",
  ),
  ServiceBankEntry(
    number: 5,
    title: "Newcomer Reception and Follow-up Seva",
    subPoints: [
      "Welcoming newcomers personally.",
      "Remembering names.",
      "Introducing them to others.",
      "Sitting with people who are alone.",
      "Understanding why they came.",
      "Following up after their first program.",
      "Inviting without pestering.",
      "Remembering exams, family situations and interests appropriately.",
      "Connecting newcomers with suitable devotees.",
      "Identifying spiritual interest.",
      "Moving people gradually rather than forcing standards prematurely.",
      "Maintaining contact records responsibly.",
      "Knowing when someone needs encouragement and when they need space.",
    ],
    assessmentQuestion: "Do newcomers feel cared for around him?",
  ),
  ServiceBankEntry(
    number: 6,
    title: "Mentoring and Devotee-Care Seva",
    subPoints: [
      "Learning to listen.",
      "Asking rather than immediately lecturing.",
      "Understanding sādhana struggles.",
      "Helping someone set realistic commitments.",
      "Following up commitments.",
      "Giving appreciation.",
      "Giving correction respectfully.",
      "Confidentiality.",
      "Healthy interpersonal boundaries.",
      "Not creating emotional dependency.",
      "Recognizing issues beyond one's competence and referring them to responsible seniors/professionals where required.",
      "Managing disagreements.",
      "Caring for someone who has become irregular.",
      "Reconnecting people without shaming them.",
      "Training a mentee eventually to care for another person.",
    ],
    assessmentQuestion: "Are people spiritually stronger after being under his care?",
    context: "Modern ISKCON leadership training explicitly treats devotee care, teamwork, empowerment, strategic planning and leadership as serious organizational competencies rather than optional extras.",
  ),
  ServiceBankEntry(
    number: 7,
    title: "Prasādam Cooking Seva",
    subPoints: [
      "Philosophy of cooking for Kṛṣṇa.",
      "Personal cleanliness.",
      "Kitchen cleanliness.",
      "Ingredient standards.",
      "Avoiding contamination.",
      "Knife and kitchen safety.",
      "Basic rice.",
      "Dāl.",
      "Sabjī.",
      "Chapāti.",
      "Snacks.",
      "Sweets.",
      "Festival preparations.",
      "Cooking for 5.",
      "Cooking for 20.",
      "Cooking for 100+.",
      "Menu planning.",
      "Quantity calculation.",
      "Purchasing.",
      "Inventory.",
      "Food storage.",
      "Time management.",
      "Team cooking.",
      "Waste minimization.",
      "Offering procedures according to local standards.",
      "Kitchen cleanup after service.",
    ],
    assessmentQuestion: "Could I safely give him responsibility for prasādam for a student program?",
    context: "Prabhupāda personally trained disciples in cooking, including standards of purity and cleanliness; his teaching also repeatedly treats cooking and offering food as genuine devotional engagement.",
  ),
  ServiceBankEntry(
    number: 8,
    title: "Prasādam Distribution and Hospitality",
    subPoints: [
      "Serving etiquette.",
      "Serving devotees before oneself when appropriate.",
      "Generosity without waste.",
      "Understanding quantities.",
      "Guest care.",
      "Drinking-water arrangements.",
      "Seating.",
      "Queue management.",
      "Cleaning serving areas.",
      "Caring for special practical dietary needs where possible.",
      "Making newcomers comfortable.",
      "Hosting visiting devotees.",
      "Guest-room readiness.",
      "Reception desk.",
      "Travel hospitality.",
      "Food-relief service.",
    ],
    nuance: "Nuance: hospitality is preaching before the lecture starts.",
    assessmentQuestion: "Does a guest feel, \u2018These people genuinely care that I have come\u2019?",
    context: "Prasādam distribution is a longstanding organized ISKCON outreach activity, not simply internal catering.",
  ),
  ServiceBankEntry(
    number: 9,
    title: "Temple and Arcana Support Seva",
    subPoints: [
      "Understanding the theology of Deity worship.",
      "Appropriate cleanliness.",
      "Temple-room etiquette.",
      "Preparing paraphernalia.",
      "Flower service.",
      "Garland making.",
      "Altar cleaning where authorized.",
      "Bhoga arrangements.",
      "Festival decoration.",
      "Dressing assistance only after adequate training and authorization.",
      "Ārati procedures where appropriately qualified.",
      "Punctuality\u2014Deity service cannot depend on one's mood.",
      "Respect for standards.",
      "Careful handling of sacred paraphernalia.",
      "Backup arrangements when a sevak is absent.",
    ],
    nuance: "Nuance: higher arcana responsibilities should be competency-based and supervised, not given merely because someone is enthusiastic.",
    assessmentQuestion: "Can he be trusted with a service where lateness or carelessness directly affects temple standards?",
    context: "Scriptural and ISKCON sources treat arcana as a structured devotional discipline with cleanliness, preparation and prescribed standards; Prabhupāda simultaneously emphasized that Deity worship should support, not displace, the movement's preaching mission.",
  ),
  ServiceBankEntry(
    number: 10,
    title: "Cleanliness, Āśrama and Facility Seva",
    subPoints: [
      "Personal hygiene.",
      "Clothing.",
      "Room cleanliness.",
      "Bed and storage discipline.",
      "Bathroom standards.",
      "Kitchen cleanliness.",
      "Temple cleaning.",
      "Shoe-rack management.",
      "Waste management.",
      "Laundry systems.",
      "Maintaining common areas.",
      "Identifying repairs.",
      "Reporting damage rather than ignoring it.",
      "Ownership of organizational property.",
      "Preparing a venue before programs.",
      "Restoring the venue after programs.",
    ],
    nuance: "Critical culture: \u201cI saw it, therefore I take responsibility,\u201d instead of \u201cIt isn't my department.\u201d",
    assessmentQuestion: "Does cleanliness improve wherever this devotee lives?",
  ),
  ServiceBankEntry(
    number: 11,
    title: "Festival and Event Management Seva",
    subPoints: [
      "Defining purpose.",
      "Audience.",
      "Program design.",
      "Budget.",
      "Venue.",
      "Permissions.",
      "Invitations.",
      "Publicity.",
      "Registration.",
      "Volunteer recruitment.",
      "Seva allocation.",
      "Speaker coordination.",
      "Kīrtana coordination.",
      "Stage.",
      "Audio-visual systems.",
      "Prasādam.",
      "Transport.",
      "Guest care.",
      "Photography/video.",
      "Timekeeping.",
      "Emergency planning.",
      "Cleanup.",
      "Feedback.",
      "Financial closure.",
      "Post-event follow-up.",
    ],
    assessmentQuestion: "Can he take an idea and convert it into an executed program without a senior chasing him continuously?",
  ),
  ServiceBankEntry(
    number: 12,
    title: "Yātrā and Pilgrimage Seva",
    subPoints: [
      "Spiritual purpose of pilgrimage.",
      "Registration.",
      "Travel bookings.",
      "Room allocation.",
      "Budgets.",
      "Attendance.",
      "Group discipline.",
      "Prasādam.",
      "Kīrtana.",
      "Kṛṣṇa-kathā.",
      "Holy-place etiquette.",
      "Caring for weaker participants.",
      "Headcounts.",
      "Emergency contacts.",
      "Time management.",
      "Communicating instructions.",
      "Maintaining spiritual atmosphere during travel.",
    ],
    assessmentQuestion: "Can he care for people, logistics and spiritual atmosphere simultaneously?",
  ),
  ServiceBankEntry(
    number: 13,
    title: "Media, Communications and Creative Seva",
    subPoints: [
      "Writing invitations.",
      "Posters.",
      "Graphic design.",
      "Photography.",
      "Video.",
      "Editing.",
      "Short-form social content.",
      "Long-form educational content.",
      "Website basics.",
      "Presentation design.",
      "Livestreaming.",
      "Audio.",
      "Recording classes.",
      "Archiving.",
      "Testimonial/story collection with permission.",
      "Communicating Kṛṣṇa consciousness appropriately for different audiences.",
      "Brand consistency.",
      "Fact-checking quotations before attributing them to Prabhupāda.",
      "Avoiding sensationalism merely for clicks.",
    ],
    assessmentQuestion: "Does the content represent Prabhupāda accurately and communicate effectively to today's student?",
  ),
  ServiceBankEntry(
    number: 14,
    title: "Administration and Systems Seva",
    subPoints: [
      "Attendance records.",
      "Student database.",
      "Follow-up tracking.",
      "Documentation.",
      "Meeting agendas.",
      "Minutes.",
      "Rosters.",
      "Seva schedules.",
      "Inventory.",
      "Purchasing.",
      "Vendor coordination.",
      "Forms.",
      "Permissions.",
      "Program calendar.",
      "Standard operating procedures.",
      "Checklists.",
      "Data backup.",
      "Handover documentation.",
      "Confidential handling of personal information.",
    ],
    nuance: "Nuance: administration is not \u201cmaterial work.\u201d Good systems protect preaching energy from chaos.",
    assessmentQuestion: "Can the system continue functioning when he is absent?",
    context: "Historical accounts explicitly describe Prabhupāda training disciples in both accounts and management, while the GBC structure places concrete responsibility for carrying out ISKCON's mission on local management.",
  ),
  ServiceBankEntry(
    number: 15,
    title: "Finance and Fundraising Seva",
    subPoints: [
      "Understanding that resources belong to the mission.",
      "Budgeting.",
      "Expense discipline.",
      "Bills and receipts.",
      "Basic bookkeeping.",
      "Reconciliation.",
      "Transparent reporting.",
      "Donation collection.",
      "Explaining projects to donors.",
      "Building donor relationships.",
      "Gratitude and reporting back.",
      "Fundraising campaigns.",
      "Sponsorship.",
      "Event fundraising.",
      "Never making false claims or exerting inappropriate spiritual pressure.",
      "Avoiding waste.",
      "Distinguishing personal money from organizational money.",
      "Developing the ability eventually to make one's preaching project financially sustainable.",
    ],
    assessmentQuestion: "Would we confidently entrust this devotee with the organization's money?",
  ),
  ServiceBankEntry(
    number: 16,
    title: "Leadership and Team-Building Seva",
    subPoints: [
      "Taking ownership.",
      "Planning.",
      "Prioritization.",
      "Delegation.",
      "Giving clear instructions.",
      "Following up.",
      "Accountability.",
      "Giving appreciation.",
      "Correction.",
      "Receiving correction.",
      "Conflict resolution.",
      "Running meetings.",
      "Decision-making.",
      "Identifying risks.",
      "Managing volunteers.",
      "Building cooperation.",
      "Not monopolizing responsibility.",
      "Training one's replacement.",
      "Producing new leaders.",
      "Working under authority.",
      "Working with peers.",
      "Leading juniors without becoming controlling.",
    ],
    assessmentQuestion: "Does responsibility grow around him, or does everything become dependent upon him?",
  ),
  ServiceBankEntry(
    number: 17,
    title: "Vaiṣṇava Character and Relationship Seva",
    subPoints: [
      "Humility.",
      "Truthfulness.",
      "Reliability.",
      "Gratitude.",
      "Respect.",
      "Clean speech.",
      "Avoiding gossip.",
      "Avoiding fault-finding.",
      "Proper dealings with seniors, peers and juniors.",
      "Emotional regulation.",
      "Apologizing when wrong.",
      "Forgiving.",
      "Keeping commitments.",
      "Appropriate boundaries in interpersonal relationships.",
      "Respectful dealings with women and men.",
      "Protecting vulnerable people.",
      "Never using spiritual authority to manipulate.",
      "Cooperation despite personality differences.",
    ],
    assessmentQuestion: "Would I happily send a newcomer to spend time with this person?",
    context: "The Nectar of Instruction places enthusiasm, patient determined endeavor, regulative principles, proper association and following the previous ācāryas among the foundations of advancement; organizational training in ISKCON likewise stresses trust, cooperation and devotee care.",
  ),
  ServiceBankEntry(
    number: 18,
    title: "Missionary Hardiness and Personal Excellence",
    subPoints: [
      "Time management.",
      "Waking/sleeping discipline.",
      "Academic responsibility.",
      "Physical stamina and reasonable self-care.",
      "Ability to tolerate inconvenience.",
      "Travel readiness.",
      "Adaptability.",
      "Working with limited resources.",
      "Remaining stable when criticized.",
      "Remaining stable when appreciated.",
      "Learning new skills quickly.",
      "Problem-solving.",
      "Not needing luxury in order to serve.",
      "Finishing what one starts.",
      "Balancing study and service responsibly.",
    ],
    assessmentQuestion: "When conditions become inconvenient, does his service collapse?",
  ),
  ServiceBankEntry(
    number: 19,
    title: "Mission Expansion and Entrepreneurship",
    subPoints: [
      "Seeing preaching opportunities without being told.",
      "Starting a campus group.",
      "Starting a weekly program.",
      "Developing a team.",
      "Finding a venue.",
      "Developing contacts.",
      "Planning finances.",
      "Developing recurring systems.",
      "Measuring results.",
      "Improving weak programs.",
      "Replicating successful programs.",
      "Creating successors.",
      "Eventually opening or strengthening a preaching center under appropriate leadership.",
    ],
    assessmentQuestion: "Can we give him a territory or responsibility and expect the mission there to grow?",
  ),
];
